### ISSUE TITLE
Formatting, Linting and Commented Codes

### ISSUE THREAD

**Issue by suatkarakusoglu** [szgrm/AnimeApp#4]
https://github.com/szgrm/AnimeApp/blob/2aee746cce215ee43f01714161e0c58b6d35e799/AnimeApp/Pages/Animes/List/AnimeListRowView.swift#L39

Mumkun mertebe comment out edilmis kod birakmayalim.

Bir de formatting ve linting icin araclar arastirip ekleyebiliriz.

**Comment by szgrm** [comment]
@suatkarakusoglu Selam, SwiftFormat aracını locale yükleyip elle çalıştırdım ancak otomatize etmedim. Araştırdığımda otomatize etmenin git hook gibi yolları varmış. Hangisini kullanmam daha iyi olur?

**Comment by suatkarakusoglu** [comment]
Farklı aşamalarda entegre edebilirsin.
Bunlardan bir tanesi dediğin pre-commit phase'i.
https://pre-commit.com/

Pre-commit hook ile commit öncesine bu komutu projede çalıştır diyebilirsin.

Ya da biraz daha kolay olan build phase'ına yerleştirebilirsin
https://github.com/nicklockwood/SwiftFormat#xcode-build-phase

Her build ile formatlanmış olur kod. Biraz daha basit ve hızlı olarak formatlamış olursun.

**Comment by szgrm** [comment]
Tamamdır teşekkür ederim.
